# Generated by Django 5.2.4 on 2025-08-08 05:33

from django.db import migrations
import random
def create_random_users(apps, schema_editor):
    CustomUser = apps.get_model("accounts","CustomUser")
    Country = apps.get_model("locations","Country")
    
    # try to get existing users
    users = list(CustomUser.objects.all())
    
    # in case there are no existing users
    if not users:
        fallback_user = CustomUser.objects.create_user(
            email = "user@example.com",
            password="testpass123"
        )
        users.append(fallback_user)
        
    
    for country in Country.objects.filter(my_user__isnull=True):
        country.my_user = random.choice(users)
        country.save()
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('accounts','0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_random_users),
    ]
