# Generated by Django 5.2.4 on 2025-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_state_gst_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='gst_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
