# Generated by Django 5.2.4 on 2025-08-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_country_my_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('my_state', 'city_code'), ('my_state', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('my_country', 'name')},
        ),
    ]
